import { StylePreset } from "@/types";

// 12 styles de base fournis avec Golddust Studio.
// Les prompts positifs/négatifs sont injectés automatiquement et cachés à l'utilisateur final.
export const DEFAULT_STYLES: StylePreset[] = [
  {
    id: "style_pixar_3d",
    name: "Pixar 3D",
    icon: "Sparkles",
    shortDescription:
      "Animation 3D Pixar, couleurs vives, personnages expressifs, éclairage subsurface",
    positivePrompt:
      "3D animated Pixar-style render, expressive stylized characters, subsurface scattering skin shading, vibrant saturated color palette, soft global illumination, rounded friendly shapes, high-end animation studio quality, cinematic depth of field",
    negativePrompt:
      "photorealistic, live-action, flat lighting, dull colors, low-poly, uncanny valley, harsh shadows",
    recommendedImageEngine: "nano_banana",
    recommendedVideoEngine: "kling_3_0",
    bestFor: ["en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_lego",
    name: "LEGO",
    icon: "Blocks",
    shortDescription: "Tout en briques LEGO, plastique brillant, studio lumineux",
    positivePrompt:
      "everything built from LEGO bricks, glossy injection-molded plastic material, LEGO minifigure characters, bright studio lighting, plastic sheen reflections, toy photography aesthetic, vibrant primary colors",
    negativePrompt: "organic textures, realistic skin, matte plastic, dark moody lighting",
    recommendedImageEngine: "nano_banana",
    recommendedVideoEngine: "kling_3_0",
    bestFor: ["en", "fr"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_playmobil",
    name: "Playmobil",
    icon: "User",
    shortDescription: "Figurines Playmobil, décors colorés, style jouet",
    positivePrompt:
      "Playmobil toy figurine characters, plastic clicky-toy aesthetic, colorful playset backgrounds, cheerful toy photography, simplified smiling faces, bright even lighting",
    negativePrompt: "realistic human anatomy, dark tones, gritty texture, photorealism",
    recommendedImageEngine: "nano_banana",
    recommendedVideoEngine: "wan_2_6",
    bestFor: ["fr"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_claymation",
    name: "Claymation",
    icon: "Hand",
    shortDescription: "Argile animée, textures artisanales, lumière douce",
    positivePrompt:
      "stop-motion claymation aesthetic, visible fingerprint textures on clay models, handmade artisanal look, soft warm studio lighting, felt and clay materials, Aardman-style character design",
    negativePrompt: "smooth CGI, digital rendering, photorealistic, glossy plastic",
    recommendedImageEngine: "flux_pro",
    recommendedVideoEngine: "wan_2_6",
    bestFor: ["en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_ghibli",
    name: "Studio Ghibli",
    icon: "Leaf",
    shortDescription: "Aquarelle animée, nature luxuriante, ambiance onirique",
    positivePrompt:
      "Studio Ghibli inspired watercolor animation style, lush hand-painted nature backgrounds, dreamlike whimsical atmosphere, soft pastel color grading, painterly clouds and light, gentle character expressions",
    negativePrompt: "CGI render, harsh contrast, photorealistic, cyberpunk, neon",
    recommendedImageEngine: "flux_pro",
    recommendedVideoEngine: "grok_video",
    bestFor: ["fr", "en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_anime_2d",
    name: "Anime 2D",
    icon: "Zap",
    shortDescription: "Animation japonaise, contours nets, couleurs saturées",
    positivePrompt:
      "2D Japanese anime animation style, crisp clean linework, cel-shaded saturated colors, dynamic anime motion lines, expressive anime eyes, studio-quality key animation frame",
    negativePrompt: "3D render, photorealistic, western cartoon, muted colors",
    recommendedImageEngine: "ideogram_v3",
    recommendedVideoEngine: "kling_3_0",
    bestFor: ["en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_hyperrealiste",
    name: "Hyper-réaliste",
    icon: "Camera",
    shortDescription: "CGI photoréaliste, éclairage cinéma, rendu 8K",
    positivePrompt:
      "hyperrealistic CGI render, photoreal skin and material shading, cinematic film lighting setup, 8K ultra-detailed texture, shallow depth of field, physically based rendering, commercial product photography quality",
    negativePrompt: "cartoon, stylized, flat shading, low detail, illustration",
    recommendedImageEngine: "flux_pro",
    recommendedVideoEngine: "seedance_2_0",
    bestFor: ["en", "fr"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_ugc",
    name: "UGC Authentique",
    icon: "Smartphone",
    shortDescription: "Tourné main, iPhone, lumière naturelle, no-filter",
    positivePrompt:
      "authentic user-generated content look, shot on iPhone handheld footage, natural available light, casual amateur framing, no color grading filter, real home or bathroom setting, candid unpolished aesthetic",
    negativePrompt: "studio lighting, professional cinematography, polished color grade, tripod-stable shot",
    recommendedImageEngine: "nano_banana",
    recommendedVideoEngine: "grok_video",
    bestFor: ["fr", "en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_tv_premium",
    name: "Publicité TV Premium",
    icon: "Tv",
    shortDescription: "Cinématographique, 4K, éclairage studio, luxe",
    positivePrompt:
      "premium television commercial cinematography, 4K broadcast quality, dramatic studio lighting setup, luxury brand aesthetic, polished color grade, smooth camera movement, high production value",
    negativePrompt: "amateur footage, handheld shake, low resolution, flat lighting",
    recommendedImageEngine: "flux_pro",
    recommendedVideoEngine: "seedance_2_0",
    bestFor: ["fr", "en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_cartoon_2d",
    name: "Cartoon 2D",
    icon: "Palette",
    shortDescription: "Dessin animé occidental, traits épais, couleurs plates",
    positivePrompt:
      "western 2D cartoon animation style, bold thick outlines, flat solid color fills, exaggerated character expressions, classic Saturday-morning cartoon aesthetic, squash-and-stretch animation feel",
    negativePrompt: "photorealistic, 3D render, painterly texture, muted tones",
    recommendedImageEngine: "ideogram_v3",
    recommendedVideoEngine: "wan_2_6",
    bestFor: ["en"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_stop_motion",
    name: "Stop Motion",
    icon: "Film",
    shortDescription: "Animation image par image, textures réelles, handmade",
    positivePrompt:
      "stop-motion animation aesthetic, frame-by-frame handmade feel, real physical material textures, subtle frame judder motion, miniature set design, tactile handcrafted props",
    negativePrompt: "smooth CGI motion, digital rendering, perfectly fluid animation",
    recommendedImageEngine: "flux_pro",
    recommendedVideoEngine: "wan_2_6",
    bestFor: ["fr"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "style_flat_design",
    name: "Flat Design Animé",
    icon: "Shapes",
    shortDescription: "Illustration vectorielle animée, minimalisme coloré",
    positivePrompt:
      "flat vector illustration animation style, minimalist geometric shapes, bold flat color palette, clean modern motion graphics, simplified iconographic characters, smooth vector-based transitions",
    negativePrompt: "photorealistic, 3D depth, textured surfaces, gradients-heavy",
    recommendedImageEngine: "ideogram_v3",
    recommendedVideoEngine: "kling_3_0",
    bestFor: ["en", "fr"],
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
];
